/**
 * A gallery of ready-made default profile pictures users can pick instead of
 * uploading a photo. Generated by DiceBear's public avatar API (PNG, no key) —
 * deterministic per seed, so each one is stable.
 */
const STYLES = [
  "avataaars", "bottts", "fun-emoji", "adventurer",
  "micah", "lorelei", "personas", "notionists",
];
const SEEDS = [
  "Nova", "Leo", "Mia", "Zoe", "Max", "Ivy", "Kai", "Sam",
  "Ada", "Rex", "Luna", "Finn", "Ruby", "Ezra", "Nina", "Theo",
];

export const DEFAULT_AVATARS: string[] = SEEDS.map(
  (seed, i) =>
    `https://api.dicebear.com/7.x/${STYLES[i % STYLES.length]}/png?seed=${encodeURIComponent(seed)}`,
);
